name: 自动统计 GitHub Star

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 8 点执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Star 统计工具
        uses: fbuireu/github-star-tracker@v1
        with:
          github-token: ${{ secrets.STAR_TRACKER    }}
          locale: zh-CN
